# Generated by Django 5.2.6 on 2025-09-06 06:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('days_since_last_order', models.PositiveIntegerField(blank=True, null=True)),
                ('order_frequency_days', models.PositiveIntegerField(blank=True, null=True)),
                ('customer_segment', models.CharField(choices=[('new', 'New Customer'), ('regular', 'Regular Customer'), ('vip', 'VIP Customer'), ('at_risk', 'At Risk'), ('inactive', 'Inactive')], default='new', max_length=20)),
                ('preferred_categories', models.JSONField(default=list)),
                ('preferred_payment_method', models.CharField(blank=True, max_length=50)),
                ('return_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('complaint_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('forecast_horizon', models.PositiveIntegerField(default=4)),
                ('arima_p', models.PositiveIntegerField()),
                ('arima_d', models.PositiveIntegerField()),
                ('arima_q', models.PositiveIntegerField()),
                ('aic', models.FloatField()),
                ('bic', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mae', models.FloatField()),
                ('mape', models.FloatField()),
                ('forecasted_demand', models.JSONField()),
                ('confidence_intervals', models.JSONField()),
                ('training_data_start', models.DateField()),
                ('training_data_end', models.DateField()),
                ('training_data_points', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='inventory.medicine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_level', models.DecimalField(decimal_places=2, default=Decimal('95.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99.99'))])),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('holding_cost_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('optimal_reorder_point', models.PositiveIntegerField()),
                ('optimal_order_quantity', models.PositiveIntegerField()),
                ('optimal_maximum_stock', models.PositiveIntegerField()),
                ('safety_stock', models.PositiveIntegerField()),
                ('expected_holding_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_stockout_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_expected_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('demand_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='analytics.demandforecast')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_optimizations', to='inventory.medicine')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_date', models.DateField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('growth_rate', models.FloatField(blank=True, null=True)),
                ('seasonal_factor', models.FloatField(blank=True, null=True)),
                ('trend_direction', models.CharField(blank=True, choices=[('up', 'Upward'), ('down', 'Downward'), ('stable', 'Stable')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_trends', to='inventory.medicine')),
            ],
            options={
                'ordering': ['-period_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_date', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('total_medicines', models.PositiveIntegerField(default=0)),
                ('low_stock_items', models.PositiveIntegerField(default=0)),
                ('out_of_stock_items', models.PositiveIntegerField(default=0)),
                ('inventory_turnover', models.FloatField(default=0.0)),
                ('average_order_processing_time', models.FloatField(default=0.0)),
                ('customer_satisfaction_score', models.FloatField(blank=True, null=True)),
                ('prescription_verification_time', models.FloatField(default=0.0)),
                ('system_uptime', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('error_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_date'],
                'unique_together': {('period_type', 'period_date')},
            },
        ),
        migrations.AddIndex(
            model_name='demandforecast',
            index=models.Index(fields=['medicine', 'forecast_period'], name='analytics_d_medicin_eae095_idx'),
        ),
        migrations.AddIndex(
            model_name='demandforecast',
            index=models.Index(fields=['created_at'], name='analytics_d_created_783d27_idx'),
        ),
        migrations.AddIndex(
            model_name='salestrend',
            index=models.Index(fields=['medicine', 'period_type', 'period_date'], name='analytics_s_medicin_d762ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salestrend',
            unique_together={('medicine', 'period_type', 'period_date')},
        ),
    ]
