# Generated by Django 5.2.6 on 2026-06-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandforecast',
            name='exogenous_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='model_comparison',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='sarimax_results',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
