# Generated by Django 5.2.6 on 2025-09-06 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('response_time', 'Response Time'), ('cpu_usage', 'CPU Usage'), ('memory_usage', 'Memory Usage'), ('disk_usage', 'Disk Usage'), ('database_connections', 'Database Connections'), ('active_users', 'Active Users'), ('error_rate', 'Error Rate'), ('throughput', 'Throughput')], max_length=30)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('server_name', models.CharField(blank=True, max_length=100)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='production', max_length=20)),
                ('warning_threshold', models.FloatField(blank=True, null=True)),
                ('critical_threshold', models.FloatField(blank=True, null=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_type', 'recorded_at'], name='audits_syst_metric__3ad29a_idx'), models.Index(fields=['is_healthy', 'recorded_at'], name='audits_syst_is_heal_ed1561_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('password_change', 'Password Change'), ('permission_change', 'Permission Change'), ('data_export', 'Data Export'), ('data_import', 'Data Import'), ('system_config', 'System Configuration')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('function_name', models.CharField(blank=True, max_length=100)),
                ('request_path', models.CharField(blank=True, max_length=200)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audits_audi_user_id_312468_idx'), models.Index(fields=['action', 'timestamp'], name='audits_audi_action_62e832_idx'), models.Index(fields=['severity', 'timestamp'], name='audits_audi_severit_cb6306_idx'), models.Index(fields=['content_type', 'object_id'], name='audits_audi_content_a44dbe_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audits_audi_ip_addr_83f1e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_type', models.CharField(choices=[('hipaa', 'HIPAA'), ('gdpr', 'GDPR'), ('pci_dss', 'PCI DSS'), ('sox', 'SOX'), ('fda', 'FDA'), ('pharmacy_board', 'Pharmacy Board')], max_length=20)),
                ('requirement', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_compliant', models.BooleanField(default=True)),
                ('violation_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True)),
                ('action_taken', models.TextField(blank=True)),
                ('corrective_measures', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['compliance_type', 'checked_at'], name='audits_comp_complia_763c82_idx'), models.Index(fields=['is_compliant', 'checked_at'], name='audits_comp_is_comp_a5e93e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('suspicious_login', 'Suspicious Login Attempt'), ('multiple_failed_logins', 'Multiple Failed Login Attempts'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('data_breach_attempt', 'Data Breach Attempt'), ('privilege_escalation', 'Privilege Escalation Attempt'), ('sql_injection', 'SQL Injection Attempt'), ('xss_attempt', 'XSS Attempt'), ('csrf_attempt', 'CSRF Attempt'), ('file_upload_abuse', 'File Upload Abuse'), ('rate_limit_exceeded', 'Rate Limit Exceeded')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=200)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('auto_blocked', models.BooleanField(default=False)),
                ('manual_review_required', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['event_type', 'severity'], name='audits_secu_event_t_be5bfe_idx'), models.Index(fields=['status', 'detected_at'], name='audits_secu_status_04c379_idx'), models.Index(fields=['ip_address', 'detected_at'], name='audits_secu_ip_addr_420f10_idx')],
            },
        ),
    ]
