# Generated by Django 5.2.6 on 2025-12-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='units_per_box',
            field=models.PositiveIntegerField(default=1, help_text='Number of units per box (e.g., 12 units/box)'),
        ),
    ]
