# Generated by Django 5.2.6 on 2025-12-04 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gateway_type', models.CharField(choices=[('stripe', 'Stripe'), ('paymongo', 'PayMongo'), ('paypal', 'PayPal'), ('square', 'Square'), ('dragonpay', 'DragonPay'), ('cash_on_delivery', 'Cash on Delivery')], max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Only one gateway can be active at a time')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Use test/sandbox environment')),
                ('api_key_public', models.CharField(blank=True, help_text='Public/Test API Key', max_length=255)),
                ('api_key_secret', models.CharField(blank=True, help_text='Secret/Private API Key', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook signing secret', max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional gateway-specific configuration')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gateways', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.paymentgateway'),
        ),
    ]
