# Generated by Django 5.2.6 on 2025-09-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_orders_orde_custome_c9b64a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='new_payment_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='old_payment_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
