# Generated by Django 5.2.6 on 2025-12-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatushistory_new_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('boxes', 'Boxes'), ('bottles', 'Bottles'), ('strips', 'Strips'), ('units', 'Units'), ('packets', 'Packets')], default='pieces', help_text='Unit of measurement for this order item', max_length=20),
        ),
    ]
