# Generated by Django 5.2.6 on 2025-12-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('boxes', 'Boxes')], default='boxes', help_text='Unit of measurement for this order item', max_length=20),
        ),
    ]
